version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=yourpassword
      - DB_NAME=brainwave
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: brainwave
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  model:
    build: ./model
    volumes:
      - ./model:/llama-model
    command: [ "echo", "Replace me with llama start command" ]

volumes:
  pgdata:
